### ISSUE TITLE
Check responses for F1000R blog piece

### ISSUE THREAD

**Issue by sje30** [codecheckers/paper#8]
hi @nuest 

I've drafted some responses to the F1000R quetsions that Jessica sent us.  Are you able to take a quick look at them, and check over them?  If you are too busy, no problem, just let me know!

they are in https://github.com/codecheckers/paper/blob/master/interview/interview.md

**Comment by nuest** [comment]
Published at https://blog.f1000.com/2021/09/27/codecheck/
